docs: &docs "/home/user/Documents"
pics: &base_pics "/home/user/Pictures"
dl: &deep_learning "/home/user/Documents/Bibliography/CS/Machine Learning & Data Science/Deep Learning"

pdf:
  dst: *docs
  subpatterns:
    - regex: ".*deep learning.*"
      dst: *deep_learning
    - regex: ".*neural.*"
      dst: *deep_learning

docx:
  dst: *docs

jpg:
  dst: *base_pics
  subpatterns:
    - regex: ".*unsplash.*"
      dst: "/home/user/Pictures/Wallpapers"

jpeg:
  dst: *base_pics

py:
  dst: "/home/user/Code/Python"

rs:
  dst: "/home/user/Code/Rust"

ts:
  dst: "/home/user/Code/Web-Development"

go:
  dst: "/home/user/Code/Go/src/"

sh:
  dst: "/home/user/Code/Bash"
